/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthorUpdateDTO
 */
export interface AuthorUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof AuthorUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorUpdateDTO
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorUpdateDTO
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorUpdateDTO
     */
    description?: string;
}

/**
 * Check if a given object implements the AuthorUpdateDTO interface.
 */
export function instanceOfAuthorUpdateDTO(value: object): boolean {
    return true;
}

export function AuthorUpdateDTOFromJSON(json: any): AuthorUpdateDTO {
    return AuthorUpdateDTOFromJSONTyped(json, false);
}

export function AuthorUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function AuthorUpdateDTOToJSON(value?: AuthorUpdateDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'description': value['description'],
    };
}

