/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthorDTO
 */
export interface AuthorDTO {
    /**
     * 
     * @type {string}
     * @memberof AuthorDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorDTO
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorDTO
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorDTO
     */
    fullName?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorDTO
     */
    description?: string;
}

/**
 * Check if a given object implements the AuthorDTO interface.
 */
export function instanceOfAuthorDTO(value: object): boolean {
    return true;
}

export function AuthorDTOFromJSON(json: any): AuthorDTO {
    return AuthorDTOFromJSONTyped(json, false);
}

export function AuthorDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function AuthorDTOToJSON(value?: AuthorDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'fullName': value['fullName'],
        'description': value['description'],
    };
}

