/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthorAddDTO
 */
export interface AuthorAddDTO {
    /**
     * 
     * @type {string}
     * @memberof AuthorAddDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorAddDTO
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorAddDTO
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorAddDTO
     */
    description?: string;
}

/**
 * Check if a given object implements the AuthorAddDTO interface.
 */
export function instanceOfAuthorAddDTO(value: object): boolean {
    return true;
}

export function AuthorAddDTOFromJSON(json: any): AuthorAddDTO {
    return AuthorAddDTOFromJSONTyped(json, false);
}

export function AuthorAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorAddDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function AuthorAddDTOToJSON(value?: AuthorAddDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'firstName': value['firstName'],
        'lastName': value['lastName'],
        'description': value['description'],
    };
}

