/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthorRefDTO
 */
export interface AuthorRefDTO {
    /**
     * 
     * @type {string}
     * @memberof AuthorRefDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthorRefDTO
     */
    fullName?: string;
}

/**
 * Check if a given object implements the AuthorRefDTO interface.
 */
export function instanceOfAuthorRefDTO(value: object): boolean {
    return true;
}

export function AuthorRefDTOFromJSON(json: any): AuthorRefDTO {
    return AuthorRefDTOFromJSONTyped(json, false);
}

export function AuthorRefDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthorRefDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'fullName': json['fullName'] == null ? undefined : json['fullName'],
    };
}

export function AuthorRefDTOToJSON(value?: AuthorRefDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'fullName': value['fullName'],
    };
}

