/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookDTO
 */
export interface BookDTO {
    /**
     * 
     * @type {string}
     * @memberof BookDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof BookDTO
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof BookDTO
     */
    summary?: string;
    /**
     * 
     * @type {string}
     * @memberof BookDTO
     */
    authors?: string;
}

/**
 * Check if a given object implements the BookDTO interface.
 */
export function instanceOfBookDTO(value: object): boolean {
    return true;
}

export function BookDTOFromJSON(json: any): BookDTO {
    return BookDTOFromJSONTyped(json, false);
}

export function BookDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'title': json['title'] == null ? undefined : json['title'],
        'summary': json['summary'] == null ? undefined : json['summary'],
        'authors': json['authors'] == null ? undefined : json['authors'],
    };
}

export function BookDTOToJSON(value?: BookDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'title': value['title'],
        'summary': value['summary'],
        'authors': value['authors'],
    };
}

