/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookItemUpdateDTO
 */
export interface BookItemUpdateDTO {
    /**
     * 
     * @type {string}
     * @memberof BookItemUpdateDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof BookItemUpdateDTO
     */
    barCode?: string;
}

/**
 * Check if a given object implements the BookItemUpdateDTO interface.
 */
export function instanceOfBookItemUpdateDTO(value: object): boolean {
    return true;
}

export function BookItemUpdateDTOFromJSON(json: any): BookItemUpdateDTO {
    return BookItemUpdateDTOFromJSONTyped(json, false);
}

export function BookItemUpdateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookItemUpdateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'barCode': json['barCode'] == null ? undefined : json['barCode'],
    };
}

export function BookItemUpdateDTOToJSON(value?: BookItemUpdateDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'barCode': value['barCode'],
    };
}

