/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookItemDTO } from './BookItemDTO';
import {
    BookItemDTOFromJSON,
    BookItemDTOFromJSONTyped,
    BookItemDTOToJSON,
} from './BookItemDTO';

/**
 * 
 * @export
 * @interface BookItemDTOPagedResponse
 */
export interface BookItemDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof BookItemDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof BookItemDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof BookItemDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<BookItemDTO>}
     * @memberof BookItemDTOPagedResponse
     */
    data?: Array<BookItemDTO>;
}

/**
 * Check if a given object implements the BookItemDTOPagedResponse interface.
 */
export function instanceOfBookItemDTOPagedResponse(value: object): boolean {
    return true;
}

export function BookItemDTOPagedResponseFromJSON(json: any): BookItemDTOPagedResponse {
    return BookItemDTOPagedResponseFromJSONTyped(json, false);
}

export function BookItemDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookItemDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(BookItemDTOFromJSON)),
    };
}

export function BookItemDTOPagedResponseToJSON(value?: BookItemDTOPagedResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(BookItemDTOToJSON)),
    };
}

