/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookItemDTOPagedResponse } from './BookItemDTOPagedResponse';
import {
    BookItemDTOPagedResponseFromJSON,
    BookItemDTOPagedResponseFromJSONTyped,
    BookItemDTOPagedResponseToJSON,
} from './BookItemDTOPagedResponse';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface BookItemDTOPagedResponseRequestResponse
 */
export interface BookItemDTOPagedResponseRequestResponse {
    /**
     * 
     * @type {BookItemDTOPagedResponse}
     * @memberof BookItemDTOPagedResponseRequestResponse
     */
    response?: BookItemDTOPagedResponse;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof BookItemDTOPagedResponseRequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the BookItemDTOPagedResponseRequestResponse interface.
 */
export function instanceOfBookItemDTOPagedResponseRequestResponse(value: object): boolean {
    return true;
}

export function BookItemDTOPagedResponseRequestResponseFromJSON(json: any): BookItemDTOPagedResponseRequestResponse {
    return BookItemDTOPagedResponseRequestResponseFromJSONTyped(json, false);
}

export function BookItemDTOPagedResponseRequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookItemDTOPagedResponseRequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : BookItemDTOPagedResponseFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function BookItemDTOPagedResponseRequestResponseToJSON(value?: BookItemDTOPagedResponseRequestResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'response': BookItemDTOPagedResponseToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

