/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BookItemDTO
 */
export interface BookItemDTO {
    /**
     * 
     * @type {string}
     * @memberof BookItemDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof BookItemDTO
     */
    barCode?: string;
    /**
     * 
     * @type {string}
     * @memberof BookItemDTO
     */
    bookTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof BookItemDTO
     */
    bookId?: string;
}

/**
 * Check if a given object implements the BookItemDTO interface.
 */
export function instanceOfBookItemDTO(value: object): boolean {
    return true;
}

export function BookItemDTOFromJSON(json: any): BookItemDTO {
    return BookItemDTOFromJSONTyped(json, false);
}

export function BookItemDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookItemDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'barCode': json['barCode'] == null ? undefined : json['barCode'],
        'bookTitle': json['bookTitle'] == null ? undefined : json['bookTitle'],
        'bookId': json['bookId'] == null ? undefined : json['bookId'],
    };
}

export function BookItemDTOToJSON(value?: BookItemDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'barCode': value['barCode'],
        'bookTitle': value['bookTitle'],
        'bookId': value['bookId'],
    };
}

