/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookAddDTO } from './BookAddDTO';
import {
    BookAddDTOFromJSON,
    BookAddDTOFromJSONTyped,
    BookAddDTOToJSON,
} from './BookAddDTO';
import type { ErrorMessage } from './ErrorMessage';
import {
    ErrorMessageFromJSON,
    ErrorMessageFromJSONTyped,
    ErrorMessageToJSON,
} from './ErrorMessage';

/**
 * 
 * @export
 * @interface BookAddDTORequestResponse
 */
export interface BookAddDTORequestResponse {
    /**
     * 
     * @type {BookAddDTO}
     * @memberof BookAddDTORequestResponse
     */
    response?: BookAddDTO;
    /**
     * 
     * @type {ErrorMessage}
     * @memberof BookAddDTORequestResponse
     */
    errorMessage?: ErrorMessage;
}

/**
 * Check if a given object implements the BookAddDTORequestResponse interface.
 */
export function instanceOfBookAddDTORequestResponse(value: object): boolean {
    return true;
}

export function BookAddDTORequestResponseFromJSON(json: any): BookAddDTORequestResponse {
    return BookAddDTORequestResponseFromJSONTyped(json, false);
}

export function BookAddDTORequestResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookAddDTORequestResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'response': json['response'] == null ? undefined : BookAddDTOFromJSON(json['response']),
        'errorMessage': json['errorMessage'] == null ? undefined : ErrorMessageFromJSON(json['errorMessage']),
    };
}

export function BookAddDTORequestResponseToJSON(value?: BookAddDTORequestResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'response': BookAddDTOToJSON(value['response']),
        'errorMessage': ErrorMessageToJSON(value['errorMessage']),
    };
}

