/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LibrarianDTO } from './LibrarianDTO';
import {
    LibrarianDTOFromJSON,
    LibrarianDTOFromJSONTyped,
    LibrarianDTOToJSON,
} from './LibrarianDTO';

/**
 * 
 * @export
 * @interface LibrarianDTOPagedResponse
 */
export interface LibrarianDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof LibrarianDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof LibrarianDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof LibrarianDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<LibrarianDTO>}
     * @memberof LibrarianDTOPagedResponse
     */
    data?: Array<LibrarianDTO>;
}

/**
 * Check if a given object implements the LibrarianDTOPagedResponse interface.
 */
export function instanceOfLibrarianDTOPagedResponse(value: object): boolean {
    return true;
}

export function LibrarianDTOPagedResponseFromJSON(json: any): LibrarianDTOPagedResponse {
    return LibrarianDTOPagedResponseFromJSONTyped(json, false);
}

export function LibrarianDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LibrarianDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(LibrarianDTOFromJSON)),
    };
}

export function LibrarianDTOPagedResponseToJSON(value?: LibrarianDTOPagedResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(LibrarianDTOToJSON)),
    };
}

