/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LibrarianDTO
 */
export interface LibrarianDTO {
    /**
     * 
     * @type {string}
     * @memberof LibrarianDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof LibrarianDTO
     */
    firstName?: string;
    /**
     * 
     * @type {string}
     * @memberof LibrarianDTO
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof LibrarianDTO
     */
    lastName?: string;
    /**
     * 
     * @type {string}
     * @memberof LibrarianDTO
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof LibrarianDTO
     */
    position?: string;
}

/**
 * Check if a given object implements the LibrarianDTO interface.
 */
export function instanceOfLibrarianDTO(value: object): boolean {
    return true;
}

export function LibrarianDTOFromJSON(json: any): LibrarianDTO {
    return LibrarianDTOFromJSONTyped(json, false);
}

export function LibrarianDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LibrarianDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'firstName': json['firstName'] == null ? undefined : json['firstName'],
        'email': json['email'] == null ? undefined : json['email'],
        'lastName': json['lastName'] == null ? undefined : json['lastName'],
        'description': json['description'] == null ? undefined : json['description'],
        'position': json['position'] == null ? undefined : json['position'],
    };
}

export function LibrarianDTOToJSON(value?: LibrarianDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'firstName': value['firstName'],
        'email': value['email'],
        'lastName': value['lastName'],
        'description': value['description'],
        'position': value['position'],
    };
}

