/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SiteGoalEnum = {
    Yes: 'Yes',
    Partially: 'Partially',
    No: 'No'
} as const;
export type SiteGoalEnum = typeof SiteGoalEnum[keyof typeof SiteGoalEnum];


export function instanceOfSiteGoalEnum(value: any): boolean {
    return Object.values(SiteGoalEnum).includes(value);
}

export function SiteGoalEnumFromJSON(json: any): SiteGoalEnum {
    return SiteGoalEnumFromJSONTyped(json, false);
}

export function SiteGoalEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteGoalEnum {
    return json as SiteGoalEnum;
}

export function SiteGoalEnumToJSON(value?: SiteGoalEnum | null): any {
    return value as any;
}

