/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SiteDifficultyEnum = {
    VeryEasy: 'VeryEasy',
    Easy: 'Easy',
    Difficult: 'Difficult',
    VeryDifficult: 'VeryDifficult'
} as const;
export type SiteDifficultyEnum = typeof SiteDifficultyEnum[keyof typeof SiteDifficultyEnum];


export function instanceOfSiteDifficultyEnum(value: any): boolean {
    return Object.values(SiteDifficultyEnum).includes(value);
}

export function SiteDifficultyEnumFromJSON(json: any): SiteDifficultyEnum {
    return SiteDifficultyEnumFromJSONTyped(json, false);
}

export function SiteDifficultyEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteDifficultyEnum {
    return json as SiteDifficultyEnum;
}

export function SiteDifficultyEnumToJSON(value?: SiteDifficultyEnum | null): any {
    return value as any;
}

