/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRoleEnum } from './UserRoleEnum';
import {
    UserRoleEnumFromJSON,
    UserRoleEnumFromJSONTyped,
    UserRoleEnumToJSON,
} from './UserRoleEnum';

/**
 * 
 * @export
 * @interface UserAddDTO
 */
export interface UserAddDTO {
    /**
     * 
     * @type {string}
     * @memberof UserAddDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAddDTO
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAddDTO
     */
    password?: string;
    /**
     * 
     * @type {UserRoleEnum}
     * @memberof UserAddDTO
     */
    role?: UserRoleEnum;
}

/**
 * Check if a given object implements the UserAddDTO interface.
 */
export function instanceOfUserAddDTO(value: object): boolean {
    return true;
}

export function UserAddDTOFromJSON(json: any): UserAddDTO {
    return UserAddDTOFromJSONTyped(json, false);
}

export function UserAddDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserAddDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'role': json['role'] == null ? undefined : UserRoleEnumFromJSON(json['role']),
    };
}

export function UserAddDTOToJSON(value?: UserAddDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'email': value['email'],
        'password': value['password'],
        'role': UserRoleEnumToJSON(value['role']),
    };
}

