/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
} from './UserDTO';

/**
 * 
 * @export
 * @interface UserDTOPagedResponse
 */
export interface UserDTOPagedResponse {
    /**
     * 
     * @type {number}
     * @memberof UserDTOPagedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof UserDTOPagedResponse
     */
    pageSize?: number;
    /**
     * 
     * @type {number}
     * @memberof UserDTOPagedResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {Array<UserDTO>}
     * @memberof UserDTOPagedResponse
     */
    data?: Array<UserDTO>;
}

/**
 * Check if a given object implements the UserDTOPagedResponse interface.
 */
export function instanceOfUserDTOPagedResponse(value: object): boolean {
    return true;
}

export function UserDTOPagedResponseFromJSON(json: any): UserDTOPagedResponse {
    return UserDTOPagedResponseFromJSONTyped(json, false);
}

export function UserDTOPagedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserDTOPagedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'page': json['page'] == null ? undefined : json['page'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(UserDTOFromJSON)),
    };
}

export function UserDTOPagedResponseToJSON(value?: UserDTOPagedResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'page': value['page'],
        'pageSize': value['pageSize'],
        'totalCount': value['totalCount'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(UserDTOToJSON)),
    };
}

