/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRegisterDTO
 */
export interface UserRegisterDTO {
    /**
     * 
     * @type {string}
     * @memberof UserRegisterDTO
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterDTO
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterDTO
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterDTO
     */
    confirmPassword?: string;
}

/**
 * Check if a given object implements the UserRegisterDTO interface.
 */
export function instanceOfUserRegisterDTO(value: object): boolean {
    return true;
}

export function UserRegisterDTOFromJSON(json: any): UserRegisterDTO {
    return UserRegisterDTOFromJSONTyped(json, false);
}

export function UserRegisterDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRegisterDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'email': json['email'] == null ? undefined : json['email'],
        'password': json['password'] == null ? undefined : json['password'],
        'confirmPassword': json['confirmPassword'] == null ? undefined : json['confirmPassword'],
    };
}

export function UserRegisterDTOToJSON(value?: UserRegisterDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'email': value['email'],
        'password': value['password'],
        'confirmPassword': value['confirmPassword'],
    };
}

