/* tslint:disable */
/* eslint-disable */
/**
 * MobyLab Web App
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserRegisterDTO
 */
export interface UserRegisterDTO {
    /**
     * 
     * @type {string}
     * @memberof UserRegisterDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterDTO
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterDTO
     */
    password?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserRegisterDTO
     */
    confirmPassword?: string | null;
}

/**
 * Check if a given object implements the UserRegisterDTO interface.
 */
export function instanceOfUserRegisterDTO(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserRegisterDTOFromJSON(json: any): UserRegisterDTO {
    return UserRegisterDTOFromJSONTyped(json, false);
}

export function UserRegisterDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserRegisterDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'confirmPassword': !exists(json, 'confirmPassword') ? undefined : json['confirmPassword'],
    };
}

export function UserRegisterDTOToJSON(value?: UserRegisterDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'email': value.email,
        'password': value.password,
        'confirmPassword': value.confirmPassword,
    };
}

